# Generated by Django 5.2.13 on 2026-04-07 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTechStackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Home tech stack item',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('external_image_url', models.URLField(blank=True, help_text='If no uploaded image, paste a full image URL (e.g. CDN).', max_length=500)),
                ('live_demo_url', models.URLField(blank=True, max_length=500, verbose_name='Live demo URL')),
                ('github_url', models.URLField(blank=True, max_length=500)),
                ('featured', models.BooleanField(default=False)),
                ('list_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in lists.')),
                ('overview', models.TextField()),
                ('problem', models.TextField()),
                ('solution', models.TextField()),
            ],
            options={
                'ordering': ['list_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='TechTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, help_text='Optional grouping, e.g. frontend, backend.', max_length=80)),
            ],
            options={
                'verbose_name': 'Tech tag',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author_name', models.CharField(max_length=120)),
                ('author_role', models.CharField(max_length=120)),
                ('author_company', models.CharField(max_length=120)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('position', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='cms.project')),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ProjectScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('external_image_url', models.URLField(blank=True, max_length=500)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='cms.project')),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tech_links', to='cms.project')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.techtag')),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='tech_tags',
            field=models.ManyToManyField(blank=True, related_name='projects', through='cms.ProjectTech', to='cms.techtag'),
        ),
        migrations.AddConstraint(
            model_name='projecttech',
            constraint=models.UniqueConstraint(fields=('project', 'tag'), name='uniq_project_tag'),
        ),
    ]
