# Generated by Django 5.2.13 on 2026-04-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='external_image_url',
            field=models.URLField(blank=True, help_text='Optional URL if you do not upload a hero image. Otherwise leave blank and use Image or Screenshots.', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False, help_text='If checked, project is eligible for the home page “Featured projects” block (first 3 by list order).'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Hero image for project cards and case study banner. If empty, the first screenshot is used.', null=True, upload_to='projects/'),
        ),
    ]
