# Generated by Django 5.2.13 on 2026-04-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_project_field_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='external_image_url',
            field=models.URLField(blank=True, help_text='Optional fallback URL for cards/banner only if there is no hero Image and no Screenshots with an image.', max_length=500),
        ),
    ]
