# Generated by Django 5.2.13 on 2026-04-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_external_url_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectscreenshot',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a file here, then Save. To replace it, choose another file (or clear and save).', null=True, upload_to='screenshots/'),
        ),
    ]
