# Generated by Django 5.2.13 on 2026-04-08 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_screenshot_image_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='card_thumbnail',
            field=models.ForeignKey(blank=True, help_text='Pick one of this project’s screenshots to use on the home “Featured” and /projects cards. Leave blank to auto-pick: hero Image → first screenshot → external URL.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.projectscreenshot', verbose_name='Card / featured image'),
        ),
    ]
