# Generated by Django 5.2.13 on 2026-04-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_project_card_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, help_text='Portrait shown in the landing page hero. Square or portrait photos work best.', null=True, upload_to='profile/')),
                ('profile_image_alt', models.CharField(blank=True, default='', help_text='Alt text for the hero image (accessibility).', max_length=200)),
            ],
            options={
                'verbose_name': 'Site profile',
                'verbose_name_plural': 'Site profile',
            },
        ),
    ]
