# Generated by Django 5.2.13 on 2026-04-14 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_site_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='resume',
            field=models.FileField(blank=True, help_text='PDF resume. Shown on the public Resume page and linked from the site navigation.', null=True, upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
